version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE=https://apitest.timefly.dev
    # Opcional: mount para desarrollo con hot reload
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped

  # Opcional: servicio de desarrollo con hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_BASE=https://apitest.timefly.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: bun run dev
    profiles:
      - dev 